### ISSUE TITLE
Get wifi rssi signal strength from ABOUT page

### ISSUE THREAD

**Issue by frtz13** [patience4711/read-APSystems-YC600-QS1-DS3#134]
This is not an issue, just a hint for Home Assistant users.
Home Assistant users, who want to track WiFi rssi values, and other information provided on the ABOUT page: you may consider using the Multiscrape integration.
Use HACS to install it.
Then add the following to your configuration file:
```
multiscrape:
  - name: ECU scraper
    resource: http://[IP address of the ESP-ECU]/ABOUT
    scan_interval: 900
    authentication: digest
    username: admin
    password: !secret ecu_admin_password
    log_response: false
    sensor:
      - unique_id: ecu_wifi_rssi
        name: ECU wifi rssi
        select: "body > center:nth-child(2) > table > tr:nth-child(6) > td:nth-child(2)"
        value_template: '{{ value.split("dB")[0] | int }}'
        unit_of_measurement: "dB"
        icon: "mdi:signal"
        attributes:
          - name: uptime
            select: "body > center:nth-child(2) > table > tr:nth-child(5) > td:nth-child(2)"
        on_error:
            log: false
            value: none
```
Don't forget to put the ecu_admin_password into your secrets file.
This configuration works with ESP-ECU version 10_8. It provides a sensor with the rssi value, and the uptime as an attribute.
This has been running for 6 weeks now and does not seem to affect the stability the ESP-ECU.
