### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by github-iw** [patience4711/read-APSystems-YC600-QS1-DS3#43]
Thank you very much @patience4711 for this project which helped me (after some failed attempts) to read values from my QS1 and YC600 inverter. ESP8266 and zigbee network are up now and I can publish values to home assistant. As I'm not that familiair how to split the MQTT message into values per panel, can someone share his code from HomeAssistant?

code:

mqtt:
  sensor:
    - state_topic: "homeassistant/solar"
      name: "Zonnepanelen_1"
      unique_id: "solar_1"
      device_class: "energy"
      state_class: "measurement"
      unit_of_measurement: "W"
      value_template: "{{ value_json.p0 }}"

Hope I posted this in the correct place as it is not a real issue related to the softwarepackage itself

**Comment by frtz13** [comment]
In H.A., I made an automation for each inverter.
```
alias: PV_prod_inv1
description: ""
trigger:
  - platform: mqtt
    topic: homeassistant/solar
    value_template: "{{ value_json.inv_serial }}"
    payload: "inv1_serialnumber"
condition: []
action:
  - service: mqtt.publish
    data:
      topic: homeassistant/solar/inv1
      payload: "{{ trigger.payload }}"
      retain: true
mode: parallel
max: 2
```
analog for inv2. you will get data from each inverter in seperate mqtt topics.
